universe: [BTCUSD, ETHUSD]
least_duration: 180d

datasets:

- name: prices
  source: binance_futures
  category: candle_usdt
  field: close
  exchange: binance
  symbol_type: LINEAR_PERP
  quote: USDT
  interval: 5m
  overwrite_count: 9
  untrusted_count: 99
- name: lsr
  source: binance_futures
  category: global_long_short_account_ratio_usdt
  field: longAccount
  exchange: binance
  symbol_type: LINEAR_PERP
  quote: USDT
  interval: 5m
  overwrite_count: 9
  untrusted_count: 99

alpha:
  name: test_sum_ts_1
  class: test_alpha.AlphaSumTs1
  # parameters
  interval: 5m
